### ISSUE TITLE
Improve photo/video upload

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-backend#137]
Video especially, it takes 10 minutes to upload a 10 second video on the devserver

Rework so that it works like this:
- Phone requests upload url
- Server answers with upload url (which is an url to cloudstorage) (& serving url?)
- When fully uploaded, phone executes the sendMessage call like it is now, but the url will now be one from cloudstorage.

**Comment by bart-at-mobicage** [comment]
@lucasvanhalst, this PR #140, right?

**Comment by lucasvanhalst** [comment]
correct
