### ISSUE TITLE
Hidden items returned by server

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#183]
In the "Actions" feed, we hid "OSA Bakker". When refreshing the view (pull-down and also going back and opening the feed again), the server kept returning items of "OSA Bakker".

Happened for `maureen@onzestadapp.be:osa-demo2`

<img width="300px" src="https://user-images.githubusercontent.com/17762105/55729246-13d4bc00-5a16-11e9-9de1-9846026f8fa5.jpg"/> <img width="300px" src="https://user-images.githubusercontent.com/17762105/55729244-13d4bc00-5a16-11e9-95d7-2174814673af.jpg"/>

**Comment by RubenMattan** [comment]
not a bug on the server

**Comment by bart-at-mobicage** [comment]
The first time it took more than 1 hour though. Then 3 minutes ago maureen accidentally clicked "Undo" and then hid the items again. But now they're not returned anymore. Strange tbh :/

**Comment by bart-at-mobicage** [comment]
I think it's a race conditions of defers. I now quickly hid and showed OSA Bakker, and only 1 of the news items is returned.
