### ISSUE TITLE
Empty news group tab

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#184]
The tab "Regional actions" is empty for `maureen@onzestadapp.be:osa-demo2`, but not empty for `bart+1@mobicage.com:osa-demo2`. 
There are no services hidden in "Regional actions" ("OSA Bakker" is hidden in "Local actions" though, but is probably irrelevant).

<img width="300px" src="https://user-images.githubusercontent.com/17762105/55730052-a6c22600-5a17-11e9-8200-f6ab75638b68.JPG"/> <img width="300px" src="https://user-images.githubusercontent.com/17762105/55729919-54810500-5a17-11e9-90ee-111abc5ca739.jpg"/>

**Comment by RubenMattan** [comment]
@bart-at-mobicage did you complete your profile setup with age and gender?

**Comment by bart-at-mobicage** [comment]
`maureen@onzestadapp.be:osa-demo2` has no age/gender

**Comment by bart-at-mobicage** [comment]
Ok not an issue, it does have a target audience.
