### ISSUE TITLE
News badges aren't reset sometimes

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#189]
Dunno if a server issue or a client issue, but in several apps I have badge 9+ in the sidebar, and no badge on any news group.

<img width="300px" src="https://user-images.githubusercontent.com/17762105/56210183-887eaa80-6055-11e9-8a3b-bc87a2cb23dc.PNG" />
<img width="300px" src="https://user-images.githubusercontent.com/17762105/56210186-89174100-6055-11e9-9128-5d0ba6ddd83d.PNG" />
<img width="300px" src="https://user-images.githubusercontent.com/17762105/56210187-89174100-6055-11e9-8c66-1fa5c098ff3e.PNG" />

**Comment by RubenMattan** [comment]
Its a server issue.
The problem only exists for groups that have never been opened.
**last_load_request** is None for those groups and will have a badge in the sidebar but not on the group itself
