### ISSUE TITLE
Lots of TransactionFailedErrors in _create_news_item_match

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#190]
Probably because of https://github.com/our-city-app/mobicage-backend/blob/master/src/rogerthat/bizz/news/matching.py#L251

`Queue: news-matching-queue (/base/data/home/apps/e~rogerthat-server/20190415t14405.417506404685523653/add_1_monkey_patches.py:362)`
`deferred.run(rogerthat.bizz.news.matching._create_matches_for_news_item_worker,`
`             Key('mc-tracker', 'xxx:be-dilbeek', 'NewsSettingsUser', 'xxx@hotmail.com:be-dilbeek'),`
`             650847005,`
`             False)`

`2019-04-16 10:10:24.601 CEST`
`debugging_news _create_matches_for_news_id_worker user:xxx:be-dilbeek news_id:650847005 (/base/data/home/apps/e~rogerthat-server/20190415t14405.417506404685523653/rogerthat/bizz/news/matching.py:159)`

`2019-04-16 10:10:25.570 CEST`
`debugging_news _create_matches_for_news_id_worker user:xxx:be-dilbeek news_id:650847005 (/base/data/home/apps/e~rogerthat-server/20190415t14405.417506404685523653/rogerthat/bizz/news/matching.py:159)`

`2019-04-16 10:10:25.998 CEST`
`debugging_news _create_matches_for_news_id_worker user:xxx:be-dilbeek news_id:650847005 (/base/data/home/apps/e~rogerthat-server/20190415t14405.417506404685523653/rogerthat/bizz/news/matching.py:159)`

`2019-04-16 10:10:26.408 CEST`
`debugging_news _create_matches_for_news_id_worker user:xxx:be-dilbeek news_id:650847005 (/base/data/home/apps/e~rogerthat-server/20190415t14405.417506404685523653/rogerthat/bizz/news/matching.py:159)`

`2019-04-16 10:10:27.750 CEST`
`wait_for_all_pending_rpcs(): exception in check_rpc_success() (/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py:1199)`
`Traceback (most recent call last):`
`  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1194, in wait_for_all_pending_rpcs`
`    self.check_rpc_success(rpc)`
`  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1379, in check_rpc_success`
`    raise _ToDatastoreError(err)`
`TransactionFailedError: too much contention on these datastore entities. please try again. entity groups: [(app=e~rogerthat-server, mc-tracker, "service-74127436-2453-4c65-b477-4a90f8eab50e@rogerth.at"),(app=e~rogerthat-server, mc-tracker, "xxx:be-dilbeek")]`

`2019-04-16 10:10:27.751 CEST`
`suspended generator transaction(context.py:1043) raised TransactionFailedError(The transaction could not be committed. Please try again.) (/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py:468)`

**Comment by lucasvanhalst** [comment]
Also fix the ~5 datastore calls in a for loop while you're at it
due to the transaction the ndb cache is not used, so move some ds calls out of it.
