### ISSUE TITLE
Scanning QR codes doesn't work anymore

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#196]
Because we changed all BASE_URLs to rogerthat-server.appspot.com
Should we change it back to rogerth.at, or do we just add something to the build.yaml for QR codes?

Let's build all iOS and Android apps after this fix (or after all android/ios issues in the milestone are solved).

**Comment by RubenMattan** [comment]
i already changed al base urls back to rogerth.at
