### ISSUE TITLE
firebase: add support for multiple credentials

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-backend#209]
> A project is a container for apps across iOS, Android and web. While there is no restriction on number of apps within a project, adding an app can create one or more underlying OAuth 2.0 client IDs. There is a limit of around 30 client IDs that can be created within a single project.
> 
> You should ensure that all apps within a project are platform variants of the same application from an end user perspective. For example, if you develop a white label application, each independently labelled app should have its own Firebase project.

Every 30 apps we should create a new firebase project due to an arbitrary limitation on GCP.
- Add firebaseCredentials to AppSettings model (+ UI on cc)
- the handler which creates auth tokens for the apps should accept an optional parameter project_id (default rogerthat-android-client)

**Comment by bart-at-mobicage** [comment]
I would like a file upload button in control center, where the `GoogleService-Info.plist` file needs to be uploaded. It contains the project id. That way we can validate if the Firebase project exists already, or needs to be created by the control center user. We can also post the content to app-configurator to add in git. Fast and easy for the control center user imo.

```
	<key>PROJECT_ID</key>
	<string>rogerthat-android-client</string>
```

**Comment by RubenMattan** [comment]
> I would like a file upload button in control center, where the `GoogleService-Info.plist` file needs to be uploaded. It contains the project id. That way we can validate if the Firebase project exists already, or needs to be created by the control center user. We can also post the content to app-configurator to add in git. Fast and easy for the control center user imo.

If you can download the plist file the project exists, but yes i would require a upload via CC otherwise we manually need to update the app firebase_project_id

> Maybe we can also work with a file upload to create a new firebase project in control center. No idea what the config file contains.

We need firebase page next to apps page so we can add new firebase projects

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-backend/pull/212
https://github.com/our-city-app/plugin-mobicage-control-center/pull/38
https://gitlab.ourcityapp.xyz/rogerthat/app-configurator/merge_requests/5
