### ISSUE TITLE
Multiple press sources

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#240]
Make it possible to show multiple press sources. These will be shown as tabs (horizontal scrollable) with the avatar and name of the service.

![Screenshot 2019-09-30 at 10 47 17](https://user-images.githubusercontent.com/17762105/65863122-d7a06980-e36f-11e9-9ed8-67ecaaa1bf84.png)

**Comment by RubenMattan** [comment]
@bart-at-mobicage so every tab will just be the news of 1 service?
Notifications behaviour remains the same?

**Comment by bart-at-mobicage** [comment]
yes

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-backend/pull/242

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-android-client/pull/179

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-ios-client/pull/153
