### ISSUE TITLE
Final remarks GIPOD map

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#241]
- By default, show an medium-open bottom drawer
  - [x] iOS
  - [x] Android
- Allow markdown in sidebar item labels
  - [x] iOS
  - [x] Android
- Show the sidebar (again) when opening the app
  - [x] iOS
  - [x] Android
- When no address is set, show a red "fa-plus" icon
  - [x] iOS
  - [x] Android
- Show a text (`GetMapResponseTO.empty_text`, with markdown if wanted) when there are no results in the bottom drawer: 
  - NL: Er is momenteel geen hinder op deze locatie. Pas de afstand van uw adres aan of zoom een beetje uit om hinder rondom u te zien.
  - EN: There is no hindrance at this location. Change the distance of your address or zoom out a little bit to see hindrance around you.
  - [x] iOS 
  - [x] Android
  - [x] rogerthat-backend

- [x] iOS: always show red/green location based news block in news stream
- [x] iOS: when distance == 5000, show the full radius + some padding
- [x] iOS: "zoom" warning text disappears after 5s
- [x] iOS: crash when leaving the viewController because of `performSelector:afterDelay:`
- [x] Android: Don't show the header text in ProfileAddAddressActivity
- [x] Android: Show errors/warning in a view on top of the map 
  <img width="250px" src="https://user-images.githubusercontent.com/17762105/66044688-6c4ac900-e522-11e9-8cec-3c58a42f2ea2.PNG">
- [x] Server: update marker icon for 'stelling'
  <img src="https://user-images.githubusercontent.com/17762105/66047620-56400700-e528-11e9-8a16-ede3b4b6f6bc.png">
- [x] Icon/sidebar updates:
  - Position the gipod sidebar item on the top and rename to "**NEW**: Hinder rondom u"
  - Give the icon the app's secondary color
  - Use icon "cone" (which is recently added to icons.zip in rogerthat-build)
  - Only add to
    - be-aalter
    - be-beveren
    - be-horebeke
    - be-loc
    - be-maldegem
    - be-nazareth
    - be-ninove
    - be-wortegem-petegem
    - be-beringen
    - be-bocholt2
    - be-borgloon
    - be-bree
    - be-halen
    - be-hemiksem
    - be-hove
    - be-niel
    - be-putte
    - be-zandhoven
    - be-dilbeek
    - be-halle
    - be-herne
    - be-hoeilaart
    - be-anzegem
    - be-jabbeke
    - be-koksijde
    - (be-rijkevorsel)

**Comment by RubenMattan** [comment]
There is already an icon for 'Stelling' see https://github.com/our-city-app/plugin-gipod/blob/master/plugins/gipod/bizz/__init__.py#L128

**Comment by bart-at-mobicage** [comment]
I made a mistake when creating the png file that's currently on the gipod server. The 'stelling.png' icon is actually a psd file and thus it isn't shown in the app.

**Comment by lucasvanhalst** [comment]
![Screenshot 2019-10-03 at 11 19 48](https://user-images.githubusercontent.com/6652304/66114745-c8b7f200-e5cf-11e9-8611-05ec4dc7370a.png)
