### ISSUE TITLE
Direct API requests skipping the backlog

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-backend#45]
---

Migrated from https://github.com/rogerthat-platform/rogerthat-backend/issues/28
Originally created by @bart-at-mobicage on *Thu, 24 Nov 2016 13:28:40 GMT*

---

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-backend/pull/192
https://github.com/our-city-app/mobicage-android-client/pull/132
